name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install MAUI Workload
        run: dotnet workload install maui-android
      - name: Build APK
        run: |
          dotnet build "Damino 101 .az.csproj" -c Release -f net8.0-android
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Domino-APK
          path: bin/Release/net8.0-android/*-Signed.apk
